version: '3.7'

services:
  mfg-tpc-lotte-web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: 'tpc-web'
    hostname: 'tpc-web'
    restart: 'always' #on-failure
    #expose:
    #  - '4400'
    #ports:
    #  - '4400:4400'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - api_network
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.mfg-tpc-lotto-web.entrypoints=websecure"
      - "traefik.http.routers.mfg-tpc-lotto-web.entrypoints=web"
      - "traefik.http.routers.mfg-tpc-lotto-web.rule=Host(`tpc-lotto.minorfoodit.com`)"
      - "traefik.http.routers.mfg-tpc-lotto-web.service=mfg-tpc-lotto-web"
      #- "traefik.http.routers.mfg-tpc-lotto-web.tls=true"
      - "traefik.http.services.mfg-tpc-lotto-web.loadbalancer.server.port=80"
      - "traefik.docker.network=api_network"

networks:
  api_network:
    external: true